PYTHON = python

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  fetch         to fetch the data"
	@echo "  recon         to run anatomy scripts"
	@echo "  preproc        to run all scripts after anatomy. LFREQ must be set for highpass cutoff"
	@echo "  check         check if the dependencies are available"
	@echo "  preproc-log   to send the output through tee also to a logfile"
	@echo "  profile       to profile memory consumption"
	@echo "  all           to build fetch data, run anatomy scripts and all the processing scripts with no highpass"
	@echo "  clean		remove intermediate scripts generated by processing"

check:
	$(PYTHON) check_system.py

clean:
	$(PYTHON) clean.py

fetch:
	$(PYTHON) 00-fetch_data.py

recon:
	$(PYTHON) 01-anatomy.py

preproc:
	@if test "$(LFREQ)" = "" ; then \
		echo "LFREQ not set, use something like LFREQ=None make ..."; \
		exit 1; \
	fi
	$(PYTHON) 02-extract_events.py
	$(PYTHON) 03-maxwell_filtering.py
	@sed -i -E "s/.*l_freq = .*/l_freq = 1/" library/config.py
	$(PYTHON) 04-python_filtering.py
	@sed -i -E "s/.*l_freq = .*/l_freq = ${LFREQ}/" library/config.py
	$(PYTHON) 04-python_filtering.py
	$(PYTHON) 05-run_ica.py
	$(PYTHON) 06-make_epochs.py
	$(PYTHON) 07-make_evoked.py
	$(PYTHON) 08-make_cov.py
	$(PYTHON) 09-time_frequency.py
	$(PYTHON) 10-sliding_estimator.py
	$(PYTHON) 11-group_average_sensors.py
	$(PYTHON) 12-make_forward.py
	$(PYTHON) 13-make_inverse.py
	$(PYTHON) 14-group_average_source.py
	$(PYTHON) 15-lcmv_beamformer.py
	$(PYTHON) 16-group_average_lcmv.py

preproc-log:
	$(MAKE) preproc-log 2>&1 | tee log_preproc.txt

profile:
	mprof run 02-extract_events.py
	mprof plot -o extract_events
	mprof run 04-python_filtering.py
	mprof plot -o python_filtering
	mprof run 05-run_ica.py
	mprof plot -o run_ica
	mprof run 06-make_epochs.py
	mprof plot -o make_epochs
	mprof run 07-make_evoked.py
	mprof plot -o make_evoked
	mprof run 08-make_cov.py
	mprof plot -o make_cov
	mprof run 09-time_frequency.py
	mprof plot -o time_frequency
	mprof run 10-sliding_estimator.py
	mprof plot -o sliding_estimator
	mprof run 11-group_average_sensors.py
	mprof plot -o group_average_sensors
	mprof run 12-make_forward.py
	mprof plot -o make_forward
	mprof run 13-make_inverse.py
	mprof plot -o make_inverse
	mprof run 14-group_average_source.py
	mprof plot -o group_average_source

all:
	$(MAKE) fetch
	$(MAKE) recon
	@LFREQ="None" $(MAKE) preproc
