site_name: MNE Study Template
theme: material
    # palette:
    #     scheme: preference
extra_css:
    - css/extra.css
nav:
    - Introduction: index.md
    - Installation: install.md
    - Getting Started: getting_started.md
    - Configuration Options:
        - Basic settings: settings/basic.md
        - Continuous data:
            - Bad channel detection: settings/continuous_data/autobads.md
            - Maxwell filter: settings/continuous_data/maxfilter.md
            - Stimulation artifact: settings/continuous_data/stim_artifact.md
            - Frequency filtering & resampling:
                - Filtering: settings/continuous_data/filter.md
                - Resampling: settings/continuous_data/resample.md
        - Epoched data:
            - Epoching: settings/epoched_data/epochs.md
            - Amplitude-based artifact removal: settings/epoched_data/artifacts.md
            - SSP & ICA: settings/epoched_data/ssp_ica.md
            - Statistics: settings/epoched_data/statistics.md
            - Time-frequency analysis: settings/epoched_data/time_freq.md
        - Source estimation: settings/epoched_data/inverse.md

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                setup_commands:
                    - import os
                    - os.environ["MNE_BIDS_STUDY_CONFIG"] = "docs/doc-config.py"
                rendering:
                    show_source: true
                    show_if_no_docstring: false
                    show_root_heading: true
                    show_root_full_path: false
        watch:
            - .
            - ./config.py
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
