site_name: MNE Study Template
theme: material
    # palette:
    #     scheme: preference
extra_css:
    - css/extra.css
nav:
    - Introduction: index.md
    - Installation: install.md
    - Getting Started: getting_started.md
    - Configuration Options: settings.md
plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                setup_commands:
                    - import os
                    - os.environ["MNE_BIDS_STUDY_CONFIG"] = "docs/doc-config.py"
                rendering:
                    show_source: true
                    show_if_no_docstring: false
                    show_root_heading: true
        watch:
            - .
            - ./config.py
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
