## v1.11.0 (unreleased)

### :new: New features & enhancements

- Improved performance by caching BIDSPath matches for Maxwell Filter calibration and cross-talk files (#1215 by @larsoner).

[//]: # (- Whatever [`mf_filter_chpi`][mne_bids_pipeline._config.mf_filter_chpi] etc (#000 by @whoever))

[//]: # (### :warning: Behavior changes)

[//]: # (### :package: Requirements)

[//]: # (### :bug: Bug fixes)

[//]: # (### :books: Documentation)

[//]: # (### :medical_symbol: Code health and infrastructure)
