## v1.1.0-dev (unreleased)

[//]: # (### New features & enhancements)

[//]: # (- Whatever ({{ gh(000) }} by {{ authors.whoever }} )

### Behavior changes

- The `N_JOBS` parameter has been renamed [`n_jobs`](mne_bids_pipeline._config.n_jobs)
  for consistency
  ({{ gh(694) }} by {{ authors.larsoner }})

### Code health

- Code quality now checked by [ruff](https://github.com/charliermarsh/ruff)
  and [black](https://black.readthedocs.io/en/stable/)
  ({{ gh(689) }}, {{ gh(690) }}, and {{ gh(691) }} by {{ authors.larsoner }})

[//]: # (### Bug fixes)
