## v1.1.0-dev (unreleased)

[//]: # (### New features & enhancements)

[//]: # (- Whatever (#000 by @whoever )

### Behavior changes

- The `N_JOBS` parameter has been renamed [`n_jobs`](mne_bids_pipeline._config.n_jobs)
  for consistency
  ({{ gh(694) }} by {{ authors.larsoner }})

### Code health

- Code quality now checked by [ruff](https://github.com/charliermarsh/ruff)
  and [black](https://black.readthedocs.io/en/stable/)
  (#689, #690, and #691 by @larsoner)

[//]: # (### Bug fixes)
