## v1.2.0-dev (unreleased)

### :new: New features & enhancements

- We improved caching to reduce initialization time when large datasets are being processed. (#720 by @apmellot)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :warning: Behavior changes)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :medical_symbol: Code health)

[//]: # (### :bug: Bug fixes)

- Replace legacy `plot_psd()` calls with `compute_psd().plot()`
  (#725 by @drammock)
