## v1.3.0 (unreleased)

[//]: # (### :new: New features & enhancements)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :warning: Behavior changes)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :medical_symbol: Code health)

[//]: # (- Whatever (#000 by @whoever))

### :bug: Bug fixes)

- Fix pandas 2.0 compatibility (#732 by @larsoner)
- Fix bug with `mne.sys_info` insertion in reports (#732 by @larsoner)
- Always generate CSP decdoing grand average analysis if CSP decoding was used on the single-subjec level (#733 by @hoechenberger)
