## v1.4.0 (unreleased)

[//]: # (### :new: New features & enhancements)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :warning: Behavior changes)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :medical_symbol: Code health)

[//]: # (- Whatever (#000 by @whoever))

### :bug: Bug fixes

- Fix bug when `mf_reference_run != runs[0]` (#742 by @larsoner)
- Fix bug with too many JSON files found during empty room matching (#743 by @allermat)
- Fix bug with outdated info on ch_types config option (#745 by @allermat)
