## v1.8.0 (unreleased)

[//]: # (### :new: New features & enhancements)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :warning: Behavior changes)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :package: Requirements)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :bug: Bug fixes)

[//]: # (- Whatever (#000 by @whoever))

### :medical_symbol: Code health

- We removed the unused setting `shortest_event`. It was a relic of early days of the pipeline
  and hasn't been in use for a long time. (#888 by @hoechenberger)

[//]: # (- Whatever (#000 by @whoever))
