## v1.8.0 (unreleased)

[//]: # (### :new: New features & enhancements)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :warning: Behavior changes)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :package: Requirements)

[//]: # (- Whatever (#000 by @whoever))

[//]: # (### :bug: Bug fixes)

[//]: # (- Whatever (#000 by @whoever))

### :medical_symbol: Code health

- We removed the unused settings `shortest_event` and `study_name`. They were relics of early days of the pipeline
  and haven't been in use for a long time. (#888, #889 by @hoechenberger and @larsoner)

[//]: # (- Whatever (#000 by @whoever))
