name: autofix.ci

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --locked
      - run: uv lock
      - run: uv run lefthook run pre-commit --all-files
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
        if: failure() || success()
